wechicken/wechicken-frontend-2

components/login/GoogleLogin.tsx
components/login/Login.tsx
components/mainBanner/MainBanner.tsx
components/nav/Nav.tsx
library/components/Layout/Layout.tsx
library/components/alert/Alert.tsx
library/components/button/BtnLike.tsx
library/components/modal/ModalLayout.tsx
pages/_app.tsx
pages/index.tsx

- Navbar를 포함하는 Layout.tsx 작성했고, _app.tsx에서 한번에 내려줍니다.
- main index에 있는 코드에서 옮겨올 것이 있다면 추가 이동 예정입니다.
- ModalLayout을 이용해 Alert 컴포넌트를 작성했습니다. 
- 여러 곳에서 쓰이고 있어서 추후 수정사항이 생길지도.. 모릅니다..
효과를 좀 넣어봤는데.. 괜찮을지는.. (쭈굴..)

feat: Layout.tsx 생성 및 Nav UI 변경

---

components/login/GoogleLogin.tsx
components/login/Login.tsx
components/mainBanner/MainBanner.tsx
components/nav/Nav.tsx
library/components/button/Button.tsx
library/components/modal/LogoBox.tsx
library/components/modal/ModalLayout.tsx
pages/index.tsx
styles/media.ts

모바일 환경에서 로그인할 수 있도록 미디어 쿼리 적용 및 기타 메인 디자인 요소 수정

design: modal container mediaquery 적용 및 main design 수정

---

components/nav/Search.tsx

- search.tsx 미디어 쿼리 작업으로 isSearchActive true로 바꿔뒀던 것 수정

refactor: Search active 적용 수정

---

.eslintrc.js
components/addPost/AddPost.tsx
components/myGroup/customCalendar/customCalendar.tsx
components/myGroup/myGroup.model.ts
components/myGroup/myGroupBanner/myGroupBanner.tsx
components/myGroup/postsOfTheWeek/PostsOfTheWeek.tsx
library/api/errorHandle.ts
library/api/mygroup.ts
library/components/alert/Alert.tsx
library/components/modal/ModalLayout.tsx
library/constants/date.const.ts
library/constants/index.ts
library/utils/date.util.ts
library/utils/index.ts
pages/mygroup/index.tsx

- 포스트 추가하는 모달 작업
- 날짜 형식 validation을 위해서 `isValidDate` 함수 만드렀슴다
- 안하면 은정님한테 혼날것같아서 반응형도 적용했어요...
``` ts
import dayjs from 'dayjs';
import { DATE_FORMAT, DATE_REGEX } from 'library/constants';
/**
* 주어지는 문자열이 YYYY.MM.DD 형식이며, 유효한 날짜인지 체크하는 함수
* @param dateString 체크 할 날짜 문자열
*/
export const isValidDate = (dateString: string): boolean => {
const checkRegex = DATE_REGEX.test(dateString);
const dateObj = dayjs(dateString, DATE_FORMAT);
if (!checkRegex) {
return false;
}
return dateObj.isValid();
};
```
코곧내(?)
regex로 형식 체크하고 2021.14.45 이런 말도안되는 날짜 걸러주는 함숩니다!

feat: addPost 추가

---

components/myGroup/customCalendar/customCalendar.tsx
components/myGroup/postsOfTheWeek/PostsOfTheWeek.tsx
library/api/mygroup.ts
pages/mygroup/index.tsx

- 치킨계 가입하지않았을 때 group에 join하는 api 연동
- 은정님이 만들어두신 구글로그인 토큰 사용하도록 변경
- 반응형 padding px -> rem으로 변경
아......이미 가입해버려서 스샷을 찍을수가 없어요.....머쓱타드....^^;
그없

feat: joingroup 추가, css 조금 변경

---

components/login/Login.tsx
components/login/LoginForm.tsx

design: login, loginform 미디어쿼리 적용

---

components/login/GoogleLogin.tsx
components/myProfile/EditForm.tsx
components/myProfile/MyPostEditModal.tsx
components/myProfile/MyPosts.tsx
components/myProfile/ProfileColumn.tsx
components/nav/SubMenu.tsx
library/api/myprofile.ts
library/hooks/useUpload.ts
library/models/index.ts
library/models/myprofile.ts
library/store/saveUser.ts
pages/myPage/index.tsx
pages/myprofile/index.tsx

- 마이페이지 파일명을 myPage -> myprofile로 변경
- 마이프로필 코드 이관
- 내 정보, 내 포스트 가져오기
- 마이 프로필 이미지 삭제 및 수정
- 블로그 주소 수정
- 마이 포스트 삭제 및 수정
**[ !! 문제 발생(하단에 자세히 작어놓았습니다.) ]**
- 프로필 사진 수정에 오류가 있습니다.
- 내 포스트에서 내용 수정 후 포스트에 바로 적용되지 않습니다.

add: myprofile

---

.github/workflows/develop.yml
components/login/Login.tsx
library/components/card/Card.tsx
package.json
pages/_app.tsx
pages/_document.tsx
pages/_error.tsx
styles/GlobalStyles.tsx

- 서버 https 적용 전까지 AWS S3로 배포
- develop에 푸시가 되면 자동으로 S3 배포되도록 스크립트 작성
- 웹폰트 적용위해 _document.tsx 커스터마이징 추가
- 에러페이지 커스터마이징 위해 _error.tsx 추가

feat: _error, _document 페이지 추가 및 자동배포 스크립트 작성

---

.github/workflows/develop.yml
pages/_app.tsx

fix: 빌드 시 env 변수명 변경

---

components/login/GoogleLogin.tsx
components/login/LoginForm.tsx
components/myGroup/createAndModifyMyGroup/CreateOrModifyMyGroup.tsx
library/api/apiClient.ts
library/api/index.ts
library/components/Auth/AuthProvider.tsx
library/components/button/BtnLike.tsx
library/store/saveUser.ts
pages/_app.tsx
pages/index.tsx
pages/search/index.tsx

- auth provider 작성. 새로고침 시마다 session storage 체크 후 로그인 유저 리덕스 저장

feat: AuthProvider.tsx 추가 및 session storage auth 관리 추가

---

components/mainBanner/BannerContents.ts
components/mainBanner/MainBanner.tsx
library/components/Auth/AuthProvider.tsx
package.json
pages/_document.tsx
pages/index.tsx
yarn.lock

`import Flicking from '@egjs/react-flicking';`
네이버에서 만든 캐러셀 라이브러리[egjx-flicking](https://naver.github.io/egjs-flicking/) 를 추가했습니다.

feat: main banner carousel 추가

---

library/components/profileIcon/ProfileIcon.tsx
next.config.js

- 일부 유저 프로필 아이콘 표시 에러 문제 해결
- profile 사진 롤백

fix: 일부 유저 프로필 아이콘 표시 에러 문제 해결

---

components/myProfile/EditForm.tsx
components/myProfile/MyPostEditModal.tsx
components/myProfile/MyPosts.tsx
components/myProfile/ProfileColumn.tsx
components/nav/Nav.tsx
library/api/apiClient.ts
library/api/index.ts
library/api/mygroup.ts
library/api/myprofile.ts
library/components/input/inputStyle.ts
library/components/postEditor/PostEditor.tsx
library/store/saveUser.ts
pages/mygroup/index.tsx
pages/myprofile/index.tsx

- 프로필사진 수정이 제대로 되지 않던 문제 수정
-  AddPost 모달이 수정 모달이랑 똑같이 생겼길래 같은 컴포넌트 재활용하도록 변경
- 포스트 수정 시 바로 갱신되지 않던 문제 수정 (지영님 저번에 여쭤보셨던거에 2-1방법으로 해결했습니다!)
냉무

refactor: myprofile 페이지 리팩토링

---

components/login/Login.tsx
components/login/LoginForm.tsx
components/myGroup/createAndModifyMyGroup/CreateMyGroup.tsx
components/myGroup/createAndModifyMyGroup/CreateOrModifyMyGroup.tsx
components/nav/Nav.tsx
components/nav/Search.tsx
components/nav/SubMenu.tsx
library/components/button/BtnSubmit.tsx
library/components/input/InputTheme.tsx
library/components/postEditor/PostEditor.tsx

- 갤럭시 폴드, 아이폰 5/5s 화면과 같이 width 300 이하 화면의 미디어쿼리를 수정했습니다.
- Nav, CreateMyGroup, Login 컴포넌트 수정.
- modifyMyGroup 컴포넌트도 수정할 예정입니다.

design: Nav, CreateMyGroup 컴포넌트 미디어쿼리 수정

---

components/myGroup/contributors/contributor.tsx
components/myGroup/contributors/contributors.tsx
components/myGroup/myGroupBanner/myGroupBanner.tsx
components/myProfile/ProfileColumn.tsx
library/components/input/inputStyle.ts
library/components/postEditor/PostEditor.tsx
pages/mygroup/index.tsx

- 갤럭시 폴드에서 내 그룹, 마이페이지 미디어쿼리 이상하게 보이던 현상 수정
- 내 그룹 페이지 - 이 주의 공헌에서 내 프로필 사진 제대로 보이지 않던 현상 수정
해상도 width가 열라 작은 경우 이주의공헌에서 내 상태(?) 가 차지하는 공간이 넘무 커서 세로로 바꿨어여

style: 갤럭시 폴드에서 내그룹, 마이페이지 미디어쿼리 이상하게 보이던 현상 수정

---

pages/404.tsx

- Warning Fix: You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.
- 레퍼런스는 [여기](https://nextjs.org/docs/messages/custom-error-no-custom-404)

feat: 404 custom page 작성

---

components/myGroup/createAndModifyMyGroup/CreateOrModifyMyGroup.tsx
components/myGroup/createAndModifyMyGroup/ModifyMyGroup.tsx
components/nav/Nav.tsx
library/models/main.ts
pages/index.tsx
pages/mygroup/index.tsx

- 기수의 master인 경우, profile 사진 위 왕관 씌우기
- 기수 페이지에서 Navbar에 기수 이름과 master인 경우 기수 수정할 수 있는 기능 추가
- modify group modal 미디어쿼리 적용

feat: modify my group 기능 추가

---

components/myGroup/contributors/contributors.tsx

이게 진짜 최종이길......
커곧내 🤦‍♀️🤦‍♀️🤦‍♀️

style: 갤럭시 폴드에서 css 이상한거 또발견해서 수정

---

components/myProfile/MyPosts.tsx
components/myProfile/ProfileColumn.tsx
components/nav/Nav.tsx

- Nav, myProfile 미디어쿼리 수정
- sm 사이즈에서 myProfile의 text 사이즈 조정
- Nav 바에서 myGroup 이동 시 group title 보이도록 수정

design: Nav, myProfile 미디어쿼리 수정

---

components/myGroup/myGroupBanner/myGroupBanner.tsx
components/toast/Toast.tsx
library/components/Layout/Layout.tsx

md~lg 사이에서 반응형 레이아웃이 이상하던 현상을 수정했슴다

style: 내그룹페이지 반응형 이상하던거 수정

---

components/nav/SubMenu.tsx
library/api/liked.ts
pages/liked/index.tsx
pages/search/index.tsx

- 북마크/좋아요 페이지 코드 이관
- 다 차려진 밥상에..숟가락 얹기 ..^.ㅠ

add: liked page

---

library/components/input/InputTheme.tsx
library/components/input/inputStyle.ts
pages/search/index.tsx

- search page debounce 적용 오류 수정
- search input theme style 수정

fix: search page input event debounce 적용 및 design 수정

---

components/login/GoogleLogin.tsx
components/myProfile/ProfileColumn.tsx
components/toast/Toast.tsx
library/api/errorHandle.ts
library/components/button/BtnLike.tsx
library/models/toast.ts
library/store/toast.ts
pages/404.tsx
pages/_error.tsx
styles/emotion.d.ts
styles/theme.ts

- toast config에 type 추가
```ts
export type ToastConfig = {
message: string;
type: 'info' | 'like' | 'bookmark' | 'error';
duration?: number;
};
```

feat: toast type 추가 및 디자인 변경

---

.eslintignore
.github/workflows/build.yml
components/login/GoogleLogin.tsx
components/toast/Toast.tsx
library/store/toast.ts
package.json

- 구글 로그인 도중 에러가 발생한 경우 (validation error 등등...) 이후에 구글로그인 버튼이 아무런 동작을 하지 않던 문제를 해결했습니다
- pr 시에 빌드, 린트 돌려보는 액션 추가

fix: 로그인중 에러발생한 경우 구글로그인 버튼 동작안하는 문제 수정, build 액션 추가

---

components/login/GoogleLogin.tsx

[1] fix: gapi 로드 함수 가드 추가

---

components/myProfile/MyPosts.tsx
library/components/card/Card.tsx
library/components/modal/ModalLayout.tsx
pages/liked/index.tsx
styles/theme.ts

- myprofile 내 포스트 PostWrapper 수정 및 추가
- 북마크 nav css 수정

fix: 내 포스트, 북마크 포스트 postWrapper 수정 및 추가

---

components/nav/Nav.tsx

nav dropdown menu가 active일 때 border 추가

design: nav dropdown menu가 active일 때 border 추가

---

library/components/card/Card.tsx
styles/theme.ts

fix: postWrapper grid 수정

---

components/myProfile/MyPosts.tsx
components/nav/Nav.tsx
components/toast/Toast.tsx
library/components/card/Card.tsx
pages/index.tsx
pages/liked/index.tsx
pages/search/index.tsx
styles/theme.ts

fix: postWrapper grid 수정 및 nav바focus css 추가

---

README.md
library/components/card/Card.tsx

add: readme

---

README.md
components/mainBanner/BannerContents.ts
library/components/card/Card.tsx
pages/liked/index.tsx

- sm 사이즈에서 카드 사이즈 오류 현상 수정
- css 스택 추가 및 팀 이름 수정

design: card media query 사이즈 변경

---

.github/workflows/develop.yml

기존 develop 브랜치에서 배포되던 내용을 main 브랜치에서 배포되도록 수정했습니다

fix: 배포 스크립트 develop 브랜치에서 돌던 것을 main에서 돌도록 수정

---

pages/search/index.tsx

- search 중 query가 주소에 있을 때 새로고침 시 자동 동기화

fix: search 도중 새로고침 시 search value 유지

---

components/mainBanner/MainBanner.tsx
components/nav/Search.tsx
library/components/Layout/SEO.tsx
library/components/loading/Loading.tsx
pages/liked/index.tsx
pages/mygroup/index.tsx
pages/myprofile/index.tsx
pages/search/index.tsx

- SEO meta tag에 수정사항이 있어 수정하여 올립니다..
- 기타 width, font size 세부 수정 사항이 포함되어 있습니다.

fix: seo config 수정 및 세부 css 조정

---

library/components/Layout/SEO.tsx
pages/index.tsx
pages/liked/index.tsx
pages/mygroup/index.tsx
pages/myprofile/index.tsx
pages/search/index.tsx

아래 사진 처럼 나와야 정상입니다... 이번엔 제대로 되길!!

fix: seo open graph 적용되지 않는 오류 해결 및 url 설정 추가

---

library/components/Layout/SEO.tsx
pages/index.tsx
pages/liked/index.tsx
pages/mygroup/index.tsx
pages/myprofile/index.tsx
pages/search/index.tsx

hotfix: seo open graph 적용되지 않는 오류 해결 및 url 설정 추가

---

pages/_app.tsx

hotfix: seo 컴포넌트 _app.tsx 적용
진짜 마지막이다...

fix: seo 컴포넌트 _app.tsx 적용

---

server/server.js

- https 세팅 작업 with mkcert...
- https_cert 디렉토리에 mkcert를 통해 생성한 .pem 추가
- server 디렉토리에 server.js파일 추가 (추후 proxy세팅을 위해 따로 디렉토리를 생성하였습니다.)
참고 블로그
https://dev.to/nakib/using-https-on-next-js-local-development-server-bcd

feat: https 세팅

---

library/api/index.ts
pages/index.tsx

edit: search endpoint 변경

---

components/login/GoogleLogin.tsx
components/login/LoginForm.tsx
components/myGroup/contributors/contributors.tsx
components/myGroup/createAndModifyMyGroup/CreateOrModifyMyGroup.tsx
components/myProfile/ProfileColumn.tsx
components/nav/Nav.tsx
library/api/index.ts
library/components/Layout/AuthProvider.tsx
library/models/main.ts
library/store/saveUser.ts
pages/mygroup/index.tsx

- 기존 `users/login/google` api 리스폰스에서 변경된 타입을 기반으로 관련된 로직 변경했습니다.

edit: wechicken google user api data 수정에 따른 api 관련 로직 변경

---

components/login/GoogleLogin.tsx
components/nav/Nav.tsx
library/api/auth.ts
library/api/myprofile.ts
library/components/Layout/AuthProvider.tsx
library/models/auth.ts
library/models/main.ts
library/store/saveUser.ts

제곧내(?)
인터페이스 수정하고 중복해서 선언되어있는 타입정의 삭제했습니다~

fix: 목로그인/구글로그인 인터페이스 통합 및 그에따른 수정사항 수정

---

components/myProfile/ProfileColumn.tsx
library/api/myprofile.ts
library/components/card/Card.tsx

- 프로필 주소, 이미지 삭제 api 변경
- 내 포스트 수정, 삭제 api 변경
- 내 포스트 수정, 삭제 기능 버튼 출력 형태 변경 -> handlePostId, getDeleteMyPostId 유무로 분기처리

modify: 마이페이지 프로필, 내포스트 수정

---

components/login/GoogleLogin.tsx
components/mainBanner/MainBanner.tsx
library/components/Layout/Layout.tsx
pages/_app.tsx

```
import { mediaQuery } from 'styles/media';
import { theme } from 'styles/theme';
const queryClient = new QueryClient();
function MyApp({ Component, pageProps }: AppProps): JSX.Element {
return (
<SEO>
```
```
queryClient.setDefaultOptions({
queries: {
retry: 3,
refetchOnWindowFocus: false,
refetchOnMount: false,
onError: err => {
showToast({ message: `${err}`, type: 'error' });
},
},
```

refactor: 불필요 fragment 제거 및 queryClient 선언 위치 이동, queryClient default 수정
